name: e-evaluasi

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  my-job:
    name: e-evaluasi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: create env file
        run: |
          touch .env
          echo JWT_SCRET=${{ secrets.JWT_SCRET }} >> .env

      - run: bun install
      - run: bun run dev
