name: e-evaluasi

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  JWT_SCRET: ${{secrets.JWT_SCRET}}
jobs:
  my-job:
    name: e-evaluasi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: echo $JWT_SCRET
      - run: bun install
      - run: bun run dev
